services:
  api:
    container_name: dev_api
    ports:
      - 4000:4000
    environment:
      - PGUSER=habitat_user 
      - PGHOST=db
      - PGPASSWORD=pass
      - PGDATABASE=habitat
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"
  
  db:
    container_name: dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=habitat 
      - POSTGRES_USER=habitat_user
      - POSTGRES_PASSWORD=pass
volumes:
  dbdata:
networks:
  default:
    name: habitat_app